model_dir: run/
 
data:
  train_features_file: src-train-bpe-48k.txt
  train_labels_file: tgt-train-bpe-48k.txt
  eval_features_file: src-val-bpe-48k.txt
  eval_labels_file: tgt-val-bpe-48k.txt
  source_vocabulary: src-vocab-48k.txt
  target_vocabulary: tgt-vocab-48k.txt
 
train:
  save_checkpoints_steps: 100
 
  eval:
  eval_delay: 3600  
  external_evaluators: bleu
  early_stopping:
    metric: bleu
    min_improvement: 0.2
    steps: 4
infer:
    batch_size: 15